//USER
export const USER_KEY = "USER";
export const BLOCKED_USERS_KEY = "BLOCKED-USERS-LIST";
//ARTICLES
export const PUBLISHER_ARTICLES_KEY = "PUBLISHER-ARTICLES"
export const SAVED_ARTICLES_KEY = "SAVED-ARTICLES"
export const FEED_KEY = "FEED"

//TOPICS
export const TOPICS_KEY = "TOPICS";
//NOTIFICATIONS
export const NOTIFICATIONS_KEY = "NOTIFICATIONS";
export const UNSEEN_NOTIFICATIONS_COUNT = "UNSEEN-NOTIFICATION-COUNT";

//FOLLOW
export const FOLLOWING_KEY = "FOLLOWING";
export const FOLLOWERS_KEY = "FOLLOWERS";
export const FOLLOWING_COUNT_KEY = "FOLLOWING-COUNT";
export const FOLLOWERS_COUNT_KEY = "FOLLOWERS-COUNT";