//USER
export const USER_QUERY_KEY = "USER";

//ARTICLES
export const PUBLISHER_ARTICLES_KEY = "PUBLISHER-ARTICLES"
export const SAVED_ARTICLES_KEY = "SAVED-ARTICLES"
//NOTIFICATIONS
export const NOTIFICATIONS_QUERY_KEY = "NOTIFICATIONS";
export const UNSEEN_NOTIFICATIONS_COUNT = "UNSEEN-NOTIFICATION-COUNT";

//FOLLOW
export const FOLLOWING_QUERY_KEY = "FOLLOWING";
export const FOLLOWERS_QUERY_KEY = "FOLLOWERS";
export const FOLLOWING_COUNT_QUERY_KEY = "FOLLOWING-COUNT";
export const FOLLOWERS_COUNT_QUERY_KEY = "FOLLOWERS-COUNT";